blog/urls.py
from django.urls import path

from blog import views
from blog.feeds import LatestPostsFeed

app_name = "blog"
urlpatterns = [
    path("", views.PostListView.as_view(), name="post_list"),
    path(
        "<int:year>/<int:month>/<int:day>/<slug:post>/",
        views.PostDetailView.as_view(),
        name="post_detail",
    ),
    path("<int:post_id>/share/", views.PostShare.as_view(), name="post_share"),
    path("tag/<slug:tag_slug>/", views.PostListView.as_view(), name="post_list_by_tag"),
    path("feed/", LatestPostsFeed(), name="post_feed"),
    path("search/", views.PostSearchView.as_view(), name="post_search"),
]

core/urls.py
from blog.sitemaps import PostSiteMap
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path
from pages.sitemaps import StaticViewSitemap

sitemaps = {
    "posts": PostSiteMap,
    "static": StaticViewSitemap,
}

urlpatterns = [
    # django administration
    path("dj-admin/", admin.site.urls),
    # Site map
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
    # 3rd party
    path("accounts/", include("allauth.urls")),
    # local apps
    path("", include("pages.urls")),
    path("blog/", include("blog.urls", namespace="blog")),
    path("profile/", include("users.urls")),
]

blog/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse
from django.utils import timezone
from taggit.managers import TaggableManager


class PublishedManager(models.Manager):
    def get_query_set(self):
        return super(PublishedManager, self).get_queryset().filter(status="published")


class Post(models.Model):
    STATUS_CHOICES = (
        ("draft", "Draft"),
        ("published", "Published"),
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date="publish")
    author = models.ForeignKey(
        get_user_model(), on_delete=models.CASCADE, related_name="blog_posts"
    )
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default="draft")

    objects = models.Manager()
    published = PublishedManager()
    tags = TaggableManager()

    class Meta:
        ordering = ("-publish",)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse(
            "blog:post_detail",
            args=[self.publish.year, self.publish.month, self.publish.day, self.slug],
        )


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comments")

    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ("-created",)

    def __str__(self):
        return f"Comment by {self.name} on {self.post}"

blog/forms.py
import logging

from django import forms
from django.core.mail import send_mail

from blog.models import Comment

logger = logging.getLogger(__name__)


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)

    def send_email(self, title, uri):
        from_name = self.cleaned_data["name"]
        from_email = self.cleaned_data["email"]
        to_email = self.cleaned_data["to"]
        comments = self.cleaned_data["comments"]

        subject = "{0} recommends you read {1}".format(from_name, title)
        message = "Read {0} at {1}\n{2}'s comments: {3}".format(
            title,
            uri,
            from_name,
            comments,
        )
        logger.info("sending mail for sharing post...")
        send_mail(
            subject=subject,
            message=message,
            from_email=from_email,
            recipient_list=[to_email],
            fail_silently=False,
        )


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("name", "email", "body")

blog/views.py
import logging

from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.postgres.search import SearchVector
from django.db.models import Count
from django.shortcuts import get_object_or_404
from django.views.generic import DetailView, FormView, ListView
from django.views.generic.edit import FormMixin
from taggit.models import Tag

from blog.forms import CommentForm, EmailPostForm
from blog.models import Post

logger = logging.getLogger(__name__)


class PostListView(ListView):
    model = Post
    template_name = "blog/post/list.html"
    context_object_name = "posts"
    paginate_by = 9
    tag = None

    def get_queryset(self):
        queryset = super().get_queryset()
        tag_slug = self.kwargs.get("tag_slug")

        if tag_slug:
            logger.info("tag_slug: %s ", tag_slug)
            self.tag = get_object_or_404(Tag, slug=tag_slug)
            queryset = queryset.filter(tags__in=[self.tag])

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["tag"] = self.tag
        return context


class PostDetailView(FormMixin, DetailView):
    model = Post
    context_object_name = "post"
    template_name = "blog/post/detail.html"
    success_message = "Comment added successfully!"
    form_class = CommentForm

    def get_success_url(self):
        return self.get_object().get_absolute_url()

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        form.instance.post = self.get_object()
        form.save()
        messages.success(self.request, self.success_message)
        logger.info("saved comment with form %s", form)
        return super().form_valid(form)

    def get_object(self):
        return get_object_or_404(
            Post,
            slug=self.kwargs["post"],
            status="published",
            publish__year=self.kwargs["year"],
            publish__month=self.kwargs["month"],
            publish__day=self.kwargs["day"],
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["comments"] = self.get_object().comments.filter(active=True)
        context["similar_posts"] = self.get_similar_posts()
        return context

    def get_similar_posts(self):
        post = self.get_object()
        post_tags_ids = post.tags.values_list("id", flat=True)
        similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(
            id=post.id
        )
        similar_posts = similar_posts.annotate(same_tags=Count("tags")).order_by(
            "-same_tags", "-publish"
        )[:4]
        return similar_posts


class PostShare(SuccessMessageMixin, FormView):
    form_class = EmailPostForm
    template_name = "blog/post/share.html"
    success_url = "/"
    success_message = "Post shared successfully!"

    def form_valid(self, form):
        post = get_object_or_404(Post, id=self.kwargs["post_id"], status="published")
        uri = self.request.build_absolute_uri(post.get_absolute_url())

        self.success_url = post.get_absolute_url()

        form.send_email(title=post.title, uri=uri)
        return super().form_valid(form)


class PostSearchView(ListView):
    model = Post
    context_object_name = "post_list"
    template_name = "blog/search.html"
    paginate_by = 9

    def get_queryset(self):
        query = self.request.GET.get("q")
        return Post.published.annotate(
            search=SearchVector("title", "body"),
        ).filter(search=query)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["query"] = self.request.GET.get("q")
        return context

blog/templates/blog/includes/bottom-navigation.html
<!-- Navbar fixed bottom (immediate child of the page wrapper) -->
<nav class="navbar navbar-fixed-bottom">
    <!-- Navbar content with the dropup menu -->
    <div class="navbar-content">
        <div class="dropdown dropup with-arrow">
            <button class="btn" data-toggle="dropdown" type="button" id="navbar-fixed-bottom-dropdown-toggle">
                Help
                <i class="fa fa-angle-up" aria-hidden="true"></i>
            </button>
            <div class="dropdown-menu" aria-labelledby="navbar-fixed-bottom-dropdown-toggle">
                <a href="#" class="dropdown-item">Tutorials</a>
                <a href="#" class="dropdown-item">Examples</a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">Support</a>
                <a href="#" class="dropdown-item">Contact us</a>
            </div>
        </div>
    </div>
    <!-- Navbar brand -->
    <a href="#" class="navbar-brand ml-auto">
        <!-- ml-auto = margin-left: auto -->
        <img src="..." alt="...">
    </a>
    <!-- Navbar text -->
    <span class="navbar-text ml-auto">
        <!-- ml-auto = margin-left: auto -->
        &copy; Brand
    </span>
</nav>

blog/templates/blog/includes/sidebar.html
{% load blog_tags %}
!-- Sidebar -->
<div class="sidebar">
    <div class="sidebar-menu">
        <!-- Sidebar content with the search box -->
        <div class="sidebar-content">
            <form action="{% url 'blog:post_search' %}" method="GET">
                <input name="q" type="text" class="form-control" placeholder="Search" aria-label="Search">
            </form>
        </div>
        <!-- Sidebar links (with icons) and titles -->
        <h5 class="sidebar-title">Getting started</h5>
        <div class="sidebar-divider"></div>
        <a href="#" class="sidebar-link sidebar-link-with-icon active">
            <span class="sidebar-icon">
                <i class="fa fa-code" aria-hidden="true"></i>
            </span>
            Installation
        </a>
        <a href="#" class="sidebar-link sidebar-link-with-icon">
            <span class="sidebar-icon">
                <i class="fa fa-terminal" aria-hidden="true"></i>
            </span>
            CLI commands
        </a>
        <br />
        <!-- Latest Posts -->
        <h5 class="sidebar-title">Latest Posts</h5>
        <div class="sidebar-divider"></div>
        {% show_latest_posts 3 %}
        <br>
        <!-- End Latest Posts -->

        <!-- Most Commented -->
        <h5 class="sidebar-title">Most Commented Posts</h5>
        <div class="sidebar-divider"></div>
        {% get_most_commented_posts as most_commented_posts %}

        {% for post in most_commented_posts %}
        <a href="{{ post.get_absolute_url }}" class="sidebar-link sidebar-link-with-icon">
            <span class="sidebar-icon">
                <i class="fa fa-clipboard" aria-hidden="true"></i>
            </span>
            {{ post.title|truncatewords:15 }}
        </a>
        {% endfor %}

        <br>
        <!-- End Most Commented -->

        <!-- Stats -->
        <h5 class="sidebar-title">Stats</h5>
        <div class="sidebar-divider"></div>
        <a href="#" class="sidebar-link sidebar-link-with-icon">
            <span class="sidebar-icon">
                <i class="fa fa-clipboard" aria-hidden="true"></i>
            </span>
            {% total_posts %} posts total
        </a>
        <a href="{% url 'blog:post_feed' %}" class="sidebar-link sidebar-link-with-icon">
            <span class="sidebar-icon">
                <i class="fa fa-rss-square" aria-hidden="true"></i>
            </span>
            RSS
        </a>
        <a href="#" class="sidebar-link sidebar-link-with-icon">
            <span class="sidebar-icon">
                <i class="fa fa-map-o" aria-hidden="true"></i>
            </span>
            Map
        </a>
        <a href="#" class="sidebar-link sidebar-link-with-icon">
            <span class="sidebar-icon">
                <i class="fa fa-commenting-o" aria-hidden="true"></i>
            </span>
            Messenger
        </a>
        <!-- End Stats -->
    </div>
</div>

blog/templates/blog/includes/top-navigation.html
<!-- Navbar -->
<nav class="navbar justify-content-between">
    <div class="navbar-content">
        <button class="btn btn-light" type="button" onclick="halfmoon.toggleSidebar()">
            <i class="fa fa-bars" aria-hidden="true"></i>
            <span class="sr-only">Toggle sidebar</span> <!-- sr-only = show only on screen readers -->
        </button>
    </div>
    <!-- Navbar brand -->
    <a href="{% url 'blog:post_list' %}" class="navbar-brand">
        Blog
    </a>
    <button class="btn btn-action" type="button" onclick="toggleDemo()">
        <i class="far fa-moon" aria-hidden="true"></i>
        <span class="sr-only">Toggle DarkMode</span> <!-- sr-only = show only on screen readers -->

    </button>
</nav>