blog/urls.py
from django.urls import path

from blog import views
from blog.feeds import LatestPostsFeed

app_name = "blog"
urlpatterns = [
    path("", views.PostListView.as_view(), name="post_list"),
    path(
        "<int:year>/<int:month>/<int:day>/<slug:post>/",
        views.PostDetailView.as_view(),
        name="post_detail",
    ),
    path("<int:post_id>/share/", views.PostShare.as_view(), name="post_share"),
    path("tag/<slug:tag_slug>/", views.PostListView.as_view(), name="post_list_by_tag"),
    path("feed/", LatestPostsFeed(), name="post_feed"),
    path("search/", views.PostSearchView.as_view(), name="post_search"),
]

core/urls.py
from blog.sitemaps import PostSiteMap
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path
from pages.sitemaps import StaticViewSitemap

sitemaps = {
    "posts": PostSiteMap,
    "static": StaticViewSitemap,
}

urlpatterns = [
    # django administration
    path("dj-admin/", admin.site.urls),
    # Site map
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
    # 3rd party
    path("accounts/", include("allauth.urls")),
    # local apps
    path("", include("pages.urls")),
    path("blog/", include("blog.urls", namespace="blog")),
    path("profile/", include("users.urls")),
]

blog/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse
from django.utils import timezone
from taggit.managers import TaggableManager


class PublishedManager(models.Manager):
    def get_query_set(self):
        return super(PublishedManager, self).get_queryset().filter(status="published")


class Post(models.Model):
    STATUS_CHOICES = (
        ("draft", "Draft"),
        ("published", "Published"),
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date="publish")
    author = models.ForeignKey(
        get_user_model(), on_delete=models.CASCADE, related_name="blog_posts"
    )
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default="draft")

    objects = models.Manager()
    published = PublishedManager()
    tags = TaggableManager()

    class Meta:
        ordering = ("-publish",)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse(
            "blog:post_detail",
            args=[self.publish.year, self.publish.month, self.publish.day, self.slug],
        )


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comments")

    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ("-created",)

    def __str__(self):
        return f"Comment by {self.name} on {self.post}"

blog/forms.py
import logging

from django import forms
from django.core.mail import send_mail

from blog.models import Comment

logger = logging.getLogger(__name__)


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)

    def send_email(self, title, uri):
        from_name = self.cleaned_data["name"]
        from_email = self.cleaned_data["email"]
        to_email = self.cleaned_data["to"]
        comments = self.cleaned_data["comments"]

        subject = "{0} recommends you read {1}".format(from_name, title)
        message = "Read {0} at {1}\n{2}'s comments: {3}".format(
            title,
            uri,
            from_name,
            comments,
        )
        logger.info("sending mail for sharing post...")
        send_mail(
            subject=subject,
            message=message,
            from_email=from_email,
            recipient_list=[to_email],
            fail_silently=False,
        )


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("name", "email", "body")

blog/views.py
import logging

from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.postgres.search import SearchVector
from django.db.models import Count
from django.shortcuts import get_object_or_404
from django.views.generic import DetailView, FormView, ListView
from django.views.generic.edit import FormMixin
from taggit.models import Tag

from blog.forms import CommentForm, EmailPostForm
from blog.models import Post

logger = logging.getLogger(__name__)


class PostListView(ListView):
    model = Post
    template_name = "blog/post/list.html"
    context_object_name = "posts"
    paginate_by = 9
    tag = None

    def get_queryset(self):
        queryset = super().get_queryset()
        tag_slug = self.kwargs.get("tag_slug")

        if tag_slug:
            logger.info("tag_slug: %s ", tag_slug)
            self.tag = get_object_or_404(Tag, slug=tag_slug)
            queryset = queryset.filter(tags__in=[self.tag])

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["tag"] = self.tag
        return context


class PostDetailView(FormMixin, DetailView):
    model = Post
    context_object_name = "post"
    template_name = "blog/post/detail.html"
    success_message = "Comment added successfully!"
    form_class = CommentForm

    def get_success_url(self):
        return self.get_object().get_absolute_url()

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        form.instance.post = self.get_object()
        form.save()
        messages.success(self.request, self.success_message)
        logger.info("saved comment with form %s", form)
        return super().form_valid(form)

    def get_object(self):
        return get_object_or_404(
            Post,
            slug=self.kwargs["post"],
            status="published",
            publish__year=self.kwargs["year"],
            publish__month=self.kwargs["month"],
            publish__day=self.kwargs["day"],
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["comments"] = self.get_object().comments.filter(active=True)
        context["similar_posts"] = self.get_similar_posts()
        return context

    def get_similar_posts(self):
        post = self.get_object()
        post_tags_ids = post.tags.values_list("id", flat=True)
        similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(
            id=post.id
        )
        similar_posts = similar_posts.annotate(same_tags=Count("tags")).order_by(
            "-same_tags", "-publish"
        )[:4]
        return similar_posts


class PostShare(SuccessMessageMixin, FormView):
    form_class = EmailPostForm
    template_name = "blog/post/share.html"
    success_url = "/"
    success_message = "Post shared successfully!"

    def form_valid(self, form):
        post = get_object_or_404(Post, id=self.kwargs["post_id"], status="published")
        uri = self.request.build_absolute_uri(post.get_absolute_url())

        self.success_url = post.get_absolute_url()

        form.send_email(title=post.title, uri=uri)
        return super().form_valid(form)


class PostSearchView(ListView):
    model = Post
    context_object_name = "post_list"
    template_name = "blog/search.html"
    paginate_by = 9

    def get_queryset(self):
        query = self.request.GET.get("q")
        return Post.published.annotate(
            search=SearchVector("title", "body"),
        ).filter(search=query)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["query"] = self.request.GET.get("q")
        return context

blog/templates/blog/post/detail.html
{% extends 'blog/base.html' %}
{% load blog_tags %}
{% block title %}{{ post.title }}{% endblock title %}

{% block content %}
<div class="content">
    <div class="content">
        <h2 class="content-title">{{ post.title }}</h2>
        <div class="container mb-2">

            {% for tag in post.tags.all %}
            <a href="{% url 'blog:post_list_by_tag' tag.slug %}">
                <span class="badge badge-pill">{{ tag.name }}</span>
            </a>
            {% endfor %}
        </div>

        <p>Published {{ post.publish }} by {{ post.author }}</p>
        {{ post.body|markdown }}
        <a href="{% url 'blog:post_share' post.id %}" class="btn">
            <i class="fa fa-share" aria-hidden="true"></i>
            Share
        </a>
    </div>
    <hr>
    <div class="content">
        <h2 class="content-title">Similar Posts</h2>
        {% for post in similar_posts %}
        <p>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </p>
        {% empty %}
        <p>There are no similar posts yet.</p>
        {% endfor %}
    </div>
    <hr>
    <div class="content">
        <div class="d-flex justify-content-between">
            <h2 class="content-title">Comments</h2>

            {% with comments.count as total_comments %}
            {{ total_comments }}
            {% endwith %}

        </div>

        {% for comment in comments %}
        <small class="text-muted">{{ comment.name }} {{ comment.created }}</small>
        {{ comment.body|linebreaks }}
        {% empty %}
        There are no comments yet.
        {% endfor %}
    </div>
    <hr>
    <div class="content">
        <h2 class="content-title">
            Add a new comment
        </h2>
        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Save</button>
        </form>
    </div>
</div>


{% endblock content %}

blog/templates/blog/post/latest_posts.html
{% for post in latest_posts %}
<a href="{{ post.get_absolute_url }}" class="sidebar-link sidebar-link-with-icon">
    <span class="sidebar-icon">
        <i class="fa fa-book-open" aria-hidden="true"></i>
    </span>
    {{ post.title|truncatewords:15 }}
</a>
{% endfor %}

blog/templates/blog/post/list.html
{% extends 'blog/base.html' %}
{% load blog_tags %}

{% block title %}Blog{% endblock title %}

{% block content %}

{% if tag %}
<div class="content">
    <span class="badge badge-pill">{{ tag.name }}</span>
</div>
{% endif %}

{% for post in posts %}
<div class="content">
    <div class="card">
        <h2 class="card-title">
            <a href="{{ post.get_absolute_url }}">
                {{ post.title }}
            </a>
        </h2>
        <div class="container mb-2">

            {% for tag in post.tags.all %}
            <a href="{% url 'blog:post_list_by_tag' tag.slug %}">
                <span class="badge badge-pill">{{ tag.name }}</span>
            </a>
            {% endfor %}
        </div>

        <small class="text-muted">Published {{ post.publish }} by {{ post.author }}</small>
        <p>{{ post.body|markdown|truncatewords_html:30 }}</p>
    </div>
</div>
{% endfor %}

<div class="content">
    {% include 'blog/pagination.html' with page=page_obj %}
</div>
{% endblock content %}

blog/templates/blog/post/share.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}
{% block title %}Share a post{% endblock title %}

{% block content %}
<h1>Share by e-mail</h1>
<form action="" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit"></input>
</form>
{% endblock content %}