blog/urls.py
from django.urls import path

from blog import views
from blog.feeds import LatestPostsFeed

app_name = "blog"
urlpatterns = [
    path("", views.PostListView.as_view(), name="post_list"),
    path(
        "<int:year>/<int:month>/<int:day>/<slug:post>/",
        views.PostDetailView.as_view(),
        name="post_detail",
    ),
    path("<int:post_id>/share/", views.PostShare.as_view(), name="post_share"),
    path("tag/<slug:tag_slug>/", views.PostListView.as_view(), name="post_list_by_tag"),
    path("feed/", LatestPostsFeed(), name="post_feed"),
    path("search/", views.PostSearchView.as_view(), name="post_search"),
]

core/urls.py
from blog.sitemaps import PostSiteMap
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path
from pages.sitemaps import StaticViewSitemap

sitemaps = {
    "posts": PostSiteMap,
    "static": StaticViewSitemap,
}

urlpatterns = [
    # django administration
    path("dj-admin/", admin.site.urls),
    # Site map
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
    # 3rd party
    path("accounts/", include("allauth.urls")),
    # local apps
    path("", include("pages.urls")),
    path("blog/", include("blog.urls", namespace="blog")),
    path("profile/", include("users.urls")),
]

pages/urls.py
from django.urls import path

from pages.views import (AboutPageView, ContactPageView, FeedbackPageView,
                         HomePageView)

app_name = 'pages'
urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('contact/', ContactPageView.as_view(), name='contact'),
    path('feedback/', FeedbackPageView.as_view(), name='feedback'),
    path('about/', AboutPageView.as_view(), name='about'),
]

users/urls.py
from django.urls import path

from users.views import ProfileCreate, ProfileDetailView, ProfileUpdate

urlpatterns = [
    path('create/', ProfileCreate.as_view(), name='profile_create'),
    path('<uuid:pk>/', ProfileDetailView.as_view(), name='profile_detail'),
    path('<uuid:pk>/update', ProfileUpdate.as_view(), name='profile_update'),
]

users/models.py
import uuid

from django.contrib.auth import get_user_model
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.urls import reverse
from django_countries.fields import CountryField


class CustomUser(AbstractUser):
    pass


class Profile(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    bio = models.CharField(max_length=600, blank=True)
    location = models.CharField(max_length=200, blank=True)
    country = CountryField(blank_label='(select country)')
    birth_date = models.DateField(null=True, blank=True)
    user = models.OneToOneField(get_user_model(), on_delete=models.CASCADE, related_name='profile')

    def __str__(self):
        return self.bio

    def get_absolute_url(self):
        return reverse('profile_detail', args=[str(self.id)])


@receiver(post_save, sender=get_user_model())
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=get_user_model())
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

users/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserChangeForm, UserCreationForm


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ('email', 'username')


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = ('email', 'username')

users/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.views.generic import CreateView, DetailView, UpdateView

from users.models import Profile


class ProfileDetailView(LoginRequiredMixin, DetailView):
    model = Profile
    context_object_name = "profile"
    template_name = "users/profile_detail.html"


class ProfileCreate(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Profile
    fields = ["bio", "location", "country", "birth_date"]
    template_name = "users/profile_form.html"
    success_message = "Profile created successfully!"

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class ProfileUpdate(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Profile
    fields = ["bio", "location", "country", "birth_date"]
    template_name = "users/profile_update_form.html"
    success_message = "Profile updated successfully!"

users/templates/users/profile_detail.html
{% extends '_base.html' %}
{% load crispy_forms_tags %}

{% block title %}Profile{% endblock title %}
{% block appname %}Profile{% endblock appname %}

{% block content %}
<div class="container">
    <a href="{% url 'pages:home' %}" class="text-dark text-decoration-none">
        <div class="d-flex">
            <i class="fa fa-chevron-left fa-2x" aria-hidden="true"></i>
            <p class="lead ml-2">Home</p>
        </div>
    </a>
    <hr class="p-2">
    <ul>
        <li>User: {{ profile.user }}</li>
        <li>Bio: {{ profile.bio }}</li>
        <li>Country: {{ profile.country.name }} <img src="{{ profile.country.flag }}" alt=""></li>
        <li>Icon: <i class="{{ country.flag_css }}"></i></li>
        <li>Birthday: {{ profile.birth_date }}</li>
    </ul>
</div>
{% endblock content %}

users/templates/users/profile_form.html
{% extends '_base.html' %}
{% load crispy_forms_tags %}
{% block title %}Create{% endblock title %}

{% block content %}
<div class="container">
    <a href="{% url 'classroom_list' %}" class="text-dark text-decoration-none">
        <div class="d-flex">
            <i class="fa fa-chevron-left fa-2x" aria-hidden="true"></i>
            <p class="lead ml-2">Back</p>
        </div>
    </a>
    <hr class="p-2">
    <form action="" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <div class="mt-3 pt-3 d-flex justify-content-end">
            <button type="submit" class="btn btn-outline-success btn-block">Create</button>
        </div>
    </form>
</div>
{% endblock content %}

users/templates/users/profile_update_form.html
{% extends '_base.html' %}
{% load crispy_forms_tags %}

{% block title %}Update{% endblock title %}
{% block appname %}{{ profile }}{% endblock appname %}

{% block content %}
<div class="container">
    <a href="{{ profile.get_absolute_url }}" class="text-dark text-decoration-none">
        <div class="d-flex">
            <i class="fa fa-chevron-left fa-2x" aria-hidden="true"></i>
            <p class="lead ml-2">Back</p>
        </div>
    </a>
    <hr class="p-2">
    <form action="" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-light btn-outline-success btn-block">Update</button>
    </form>
</div>
{% endblock content %}